

services:
  mongodb:
    image: mongo:latest
    container_name: e-commerce-junior-mongodb
    volumes:
      - ./e-commerce-junior-mongodb/data:/data/db
    ports:
      - "27018:27017"
    networks:
      - app-network
  db:
    image: mysql:latest
    container_name: e-commerce-junior-db
    environment:
      MYSQL_ROOT_PASSWORD: Manuel15
      MYSQL_USER: root
      MYSQL_PASSWORD: Manuel15
      MYSQL_DATABASE: ecommerce
    volumes:
      - ./e-commerce-junior-db/mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./e-commerce-junior-backend
      dockerfile: Dockerfile
    container_name: e-commerce-junior-backend
    environment:
      - DB_HOST=50.87.216.45
      - DB_PORT=3306
      - DB_USER=mipymese_database
      - DB_PASSWORD=database123456
      - DB_NAME=mipymese_ecommerce
      - MONGODB_URI=mongodb://44.214.37.214:27018/majesticdb"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./e-commerce-junior-front
      dockerfile: Dockerfile
      args:
        API_URL: http://44.214.37.214:3000
        OPENAI_API_KEY: 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
    container_name: e-commerce-junior-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
